### ISSUE TITLE
doesnt work in windows

### ISSUE THREAD

**Issue by xzrvr** [MrLoLf/HoneygainAutoClaim#4]
it gives blank output in windows when there is `#!/usr/bin/env python3` but works when removed

**Comment by MrLoLf** [comment]
This line is a comment and is not affecting how the program runs. It's called a shebang. You can read about it [here ](https://docs.python.org/3.7/using/windows.html)or [here](https://stackoverflow.com/questions/7670303/purpose-of-usr-bin-python3-shebang). This line is used, so that your OS knows this is a python3 script. 
If you don't provide any more information, I'll consider this an environment problem on your site with python and not my script. I've tested this on my Windows machines and it worked fine.
